# Imagen base con Go
FROM golang:alpine

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el contenido del directorio actual al directorio de trabajo del contenedor
COPY . .

# Exponer el puerto 8080
EXPOSE 8080

# Compilar la aplicación Go
RUN go build -o main .

# Comando para ejecutar la aplicación al iniciar el contenedor
CMD ["./main"]
