# Usa la imagen oficial de Node.js como base
FROM node:14-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copia el archivo package.json y package-lock.json para instalar dependencias
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia los archivos del proyecto al contenedor
COPY . .

# Expone el puerto en el que se ejecuta la aplicación de React
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["npm", "start"]
